### ISSUE TITLE
using exiftool

### ISSUE THREAD

**Issue by Sadi58** [yeKcim/my_nautilus_scripts#2]
For your information, I have this Nautilus script (which I probably found somewhere and customized a bit) using **exiftool** instead of **jhead** which I find useful in converting the ALL UPPERCASE.JPG filenames (from some digital cameras) to lowercase as well as inserting the timestamp at the beginning:

```
#!/bin/sh
#Nautilus Script to rename EXIF photos and videos with EXIF date and time stamp inserted before filename
for arg
do
 tmp=`echo "$arg" | tr '[A-Z]' '[a-z]'`
 if [ -f $tmp ]
 then
   msg="Add EXIF Timestamp: '$tmp' already exists."
   gdialog --msgbox "$msg" 100 100
 else
  mv "$arg" "$tmp"
  mv -i "$tmp" "$(exiftool -a -s -CreateDate "$tmp" | sed -n '1p' | awk -F ': ' '{print $2}' | sed -e 's/:/-/g' -e 's/ /_/g')_"$tmp""
 fi
done
```

**Comment by yeKcim** [comment]
`apt-cache search exiftool`
libimage-exiftool-perl
libimage-info-perl
`apt-cache show libimage-info-perl | grep Installed-Size`
Installed-Size: 216
`apt-cache show libimage-exiftool-perl | grep Installed-Size`
Installed-Size: 11376
`apt-cache show jhead | grep Installed-Size`
Installed-Size: 119

what the advantage about exiftool instead of jhead?

I could probably test if there is one already installed and use this one… instead of impose my choice

**Comment by yeKcim** [comment]
because "clear exif tags" use exiftool too… So I [commit](https://github.com/yeKcim/my_nautilus_scripts/commit/4774d64fad93259ed81a781f4dc33036dff5afa4). Thanks for your comment.
